version: '3.3'

services:
  java_app:
    container_name: java_app
    image: maven:3.8.6-eclipse-temurin-17
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - java_db
    volumes:
      - ../api:/app
      - ~/.m2:/root/.m2
    working_dir: /app
    entrypoint: [
      'mvn',
      'spring-boot:run',
      '-Dspring-boot.run.jvmArguments="-agentlib:jdwp=transport=dt_socket,server=y,address=*:9090,suspend=n"'
    ]

  java_db:
    container_name: java_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
